//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_DE_PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLE_DE_PEDIDO()
        {
            this.PEDIDO_DE_VENTA = new HashSet<PEDIDO_DE_VENTA>();
        }
    
        public string ID_DETALLE_DE_PEDIDO__ID_DETALLEDEPEDIDO { get; set; }
        public string ID_PLATO { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO_DE_VENTA> PEDIDO_DE_VENTA { get; set; }
    }
}
