//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCARGADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENCARGADO()
        {
            this.CATEGORIA = new HashSet<CATEGORIA>();
        }
    
        public string ID_ENCARGADO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public Nullable<int> EDAD { get; set; }
        public Nullable<decimal> DNI { get; set; }
        public string DIRECCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATEGORIA> CATEGORIA { get; set; }
    }
}
