//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reportes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RESTAURANTEEntities : DbContext
    {
        public RESTAURANTEEntities()
            : base("name=RESTAURANTEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARTA> CARTA { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIA { get; set; }
        public virtual DbSet<DETALLE_DE_PEDIDO> DETALLE_DE_PEDIDO { get; set; }
        public virtual DbSet<ENCARGADO> ENCARGADO { get; set; }
        public virtual DbSet<INGREDIENTE> INGREDIENTE { get; set; }
        public virtual DbSet<MEDIDA> MEDIDA { get; set; }
        public virtual DbSet<NIVEL_DE_DIFICULTAD> NIVEL_DE_DIFICULTAD { get; set; }
        public virtual DbSet<PEDIDO_DE_VENTA> PEDIDO_DE_VENTA { get; set; }
        public virtual DbSet<PLATO> PLATO { get; set; }
        public virtual DbSet<RECETA> RECETA { get; set; }
        public virtual DbSet<RESTAURANTE> RESTAURANTE { get; set; }
    }
}
