//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLATO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLATO()
        {
            this.CARTA = new HashSet<CARTA>();
        }
    
        public string ID_PLATO { get; set; }
        public string ID_NDEDIDIFICULTAD { get; set; }
        public string ID_CATEGORIA { get; set; }
        public string ID_RECETA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARTA> CARTA { get; set; }
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual NIVEL_DE_DIFICULTAD NIVEL_DE_DIFICULTAD { get; set; }
        public virtual RECETA RECETA { get; set; }
    }
}
