//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECETA()
        {
            this.PLATO = new HashSet<PLATO>();
        }
    
        public string ID_RECETA { get; set; }
        public string ID_INGREDIENTE { get; set; }
        public string ID_MEDIDA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
    
        public virtual INGREDIENTE INGREDIENTE { get; set; }
        public virtual MEDIDA MEDIDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLATO> PLATO { get; set; }
    }
}
