//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESTAURANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESTAURANTE()
        {
            this.CARTA = new HashSet<CARTA>();
        }
    
        public string ID_RESTAURANTE { get; set; }
        public string ID_CARTA { get; set; }
        public string ID_PEDIDO { get; set; }
        public Nullable<decimal> NOMBRE { get; set; }
        public string UBICACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARTA> CARTA { get; set; }
        public virtual CARTA CARTA1 { get; set; }
        public virtual PEDIDO_DE_VENTA PEDIDO_DE_VENTA { get; set; }
    }
}
